<?php

namespace ContainerOgCnYgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NGHELNHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nGHELNH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nGHELNH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'encoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService', true],
        ], [
            'authenticationUtils' => '?',
            'dispatcher' => '?',
            'encoder' => '?',
        ]);
    }
}
