<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOgCnYgH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOgCnYgH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOgCnYgH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOgCnYgH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOgCnYgH\App_KernelDevDebugContainer([
    'container.build_hash' => 'OgCnYgH',
    'container.build_id' => '4fb43484',
    'container.build_time' => 1658322925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOgCnYgH');
